name: "build parrotsec cyberrange CI workflow"

on:
  push:
    branches: [ main]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month         

jobs:

  ubuntu-latest-job:
    name: "build parrotsec linux compose ubuntu latest"
    runs-on: ubuntu-latest
    env:
      composedir: "dockerfiles/parrotsec"
      composefile: "docker-compose-parrotsec-tools-forensic.yml"    
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker build parrotsec compose"
      run: |
        git clone https://github.com/githubfoam/cyberrange-parrotsec-githubactions.git && cd cyber*
        sudo docker-compose --file ${composedir}/${composefile}  up -d
        sudo docker-compose --file ${composedir}/${composefile}  ps
        sudo docker exec parrotsec-forensic ls
